### PR TITLE
Refactor folder structure

### PR DESCRIPTION
**Pull request by arsulegai**
1. Move binaries to /bin directory
2. Remove unused script file
3. Add .gitignore file

Signed-off-by: S m, Aruna <aruna.s.m@intel.com>

### CODE REVIEW

**Comment by RyanLassigBanks** [comment]
Looks fine. I'd like to re-review this once file conflict are resolved.

**Comment by arsulegai** [comment]
> Looks fine. I'd like to re-review this once file conflict are resolved.

Done

**Comment by peterschwarz** [comment]
@wkatsak Could you review this please?

**Comment by wkatsak** [comment]
This looks fine. Minor organizational changes.

Are we sure that the docker test script isn't used by anyone anymore?

**Comment by arsulegai** [comment]
> This looks fine. Minor organizational changes.
> 
> Are we sure that the docker test script isn't used by anyone anymore?

It wasn't used when the PR was raised. I do not know the current status.

**Review by peterschwarz — APPROVED** [review]

**Review by dplumb94 — APPROVED** [review]

**Pull request merged**
